
name: 'Nightly scheduler'

#scheduling the processing on 3am from monday to friday
on:
  schedule:
    - cron: '0 3 * * 1-5'
  workflow_dispatch:


#setting up python environment and directing the application to run the batch processing file
jobs:
  batch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install --upgrade pip setuptools wheel

      - run: pip install --no-cache-dir -r requirements.txt


      - run: python batch.py