
name: 'Nightly scheduler'

#scheduling the processing on 3am from monday to friday
on:
  schedule:
    - cron: '0 3 * * 1-5'
  workflow_dispatch:

permissions:
  contents: write

#setting up python environment and directing the application to run the batch processing file
jobs:
  batch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install --upgrade pip setuptools wheel

      - run: pip install --no-cache-dir -r requirements.txt

      - run: python batch.py

      # Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          # configure user
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

          # stage any file changes to be committed
          git add .

          # make commit with staged changes
          git commit -m 'batch done' || echo "No changes"

          # push the commit back up to source GitHub repository
          git push